### ISSUE TITLE
libsheenfigure.a missing

### ISSUE THREAD

**Issue by Mazyod** [mta452/SheenFigureLegacy#1]
Hey man, 
I love this project, it looks promising!

Here is the thing:
libsheenfigure.a is showing in red and seems to be missing.
I am also getting a compilation error in Xcode:
# include <ft2build.h> <--- File not found

**Comment by mta452** [comment]
Can you provide some details. Which procedure did you follow? What xcode version were you using? and which header file is missing?

Also provide full log so that I can figure out the actual issue.

**Comment by AmmarMujeeb** [comment]
yes same issue here !! i have tested on Xcode 4.4 & 4.5.2. 

"libsheenfigure.a" is highlighted in red color within "Link Binary with Libraries".

Compilation error is that ftbzip2.c is missing.......

"clang: error: no such file or directory: '/Users/Ahmed/Documents//SheenFigure-master/FreeType/src/bzip2/ftbzip2.c'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1"

is there any specific way to run the Target ?? while i have tried with all 3 Targets "Sheenfigure-iOS", "sheenfigure" & "freetype".

Thanks for such a project but wanna use it :(

**Comment by mta452** [comment]
I think you didn't read "readme". Anyhow I'll explain. First of all, you'll need to download FreeType library from its official website. Then copy its "include" and "src" folder in FreeType folder included in this project. After that, open
FreeType/include/freetype/config/ftmodule.h and comment the lines containing
the following lines:
    1. autofit_module_class
    2. t1_driver_class
    3. t1cid_driver_class
    4. pfr_driver_class
    5. t42_driver_class
    6. winfnt_driver_class
    7. pcf_driver_class
    8. psaux_module_class
    9. bdf_driver_class

The project will obviously run with "Sheenfigure-iOS" target as other two are libraries.

Hope this helps.
