### ISSUE TITLE
generateCachedPages issue

### ISSUE THREAD

**Issue by roula-misrabi** [mta452/SheenFigureLegacy#14]
Hi there,

I'm trying to load a font using your library into my iOS application.
I'm using "sheenFigureCG". I was able to use it before with some fonts.

Now I'm trying a new font, and here is the problem: Inside the method called "generateCachedPages" at:
float lineHeight = self.font.leading;

the lineHeight value gets a nan value and the application crashes.
Is there anyway I can fix this ?

Please find the font I'm using uploaded here:
http://www.fileswap.com/dl/2OFgoxe5t6/

**Comment by mta452** [comment]
Upgrade to latest version and make sure that you are providing correct path to font.

**Comment by roula-misrabi** [comment]
Now my problem is fixed. Thank you :)
