### ISSUE TITLE
Using a new type of fonts

### ISSUE THREAD

**Issue by Noor-Sarraj** [mta452/SheenFigureLegacy#5]
Hi,
Thank you for your benefit library , I want to use it for developing an iOS app that used arabic fonts, but as I read in the Readme file, the library supports only  Nastaliq or Naskh fonts, and it needs some additions for another type of fonts, could you please tell me what these additions are if I want to use it with other type of arabic fonts?

Regards, 
Noor.

**Comment by mta452** [comment]
You can use any Arabic font provided that it does not contain unsupported tables.
