### ISSUE TITLE
there is issue in releasing the objects

### ISSUE THREAD

**Issue by ghass64** [mta452/SheenFigureLegacy#9]
hello ,, am currently using the font in table that have news and the number of cell is 40 or more
but when scrolling between these cells it crashs the app because the there is somthing with releasing the objects 
my app used ARC i tried to figure out the problem and remove "retain" and "release" from the files ,, it fixes the problem a little bit but when trying much more scrolling it still the same problem 

could you help me please ?

**Comment by mta452** [comment]
Just pushed a new commit with additional classes and a new demo ios project.
Let me know if it solves the problem.
